Upgrade build.gradle file and dependencies
Infomaniak/PdfiumAndroid pull request #2
Opened 2023-11-16 09:44 UTC by tevincent

What's new in 1.9.5
* Upgrade build tools to 8.1.3
* Upgrade gradle to 8.0
* Delete package from AndroidManifest.xml and add namespace to build.gradle
* Upgrade androidx.collection to 1.3.0

2023-11-16 13:42 UTC, sirambd approved these changes

2023-11-16 13:44 UTC, sirambd commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-all.zip
try with 8.4

2023-11-16 13:46 UTC, sirambd requested changes
Wait for latest gradle version

2023-11-17 14:26 UTC, sirambd approved these changes

2023-11-17 14:26 UTC, merged

2023-11-17 18:42 UTC, odmfl commented
@tevincent @sirambd
Hi, can you implement text search in PDF in pdfium and pdfview?  This open source app based on pdfium and android pdf viewer allows you to do this, it would be great if you implemented it in your libraries

https://gitlab.com/mudlej_android/mj_pdf_reader

https://gitlab.com/mudlej_android/mj_pdf_reader/-/commit/a0d58ab8f72ea8bfe4c85cec52069c7a3e861be3

2023-11-18 14:31 UTC, VincentTe commented
Hi @odmfl , yes this is on my to-do list so it'll come out soon 🙂.